# Site settings
title: Blog
description: A little blog to know more about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tay
user_description: Hello, I'm Tay and I'm a 16-year-old boy who self-taught different concepts about the world of technology. Right now I am focused on learning hacking and Python.
user_title: Pentester & Programmer
email: taylerwilliam658@proton.me
twitter_username: 17tayyy
github_username:  17tayyy
gplus_username:  17tayyy

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
